$schema: https://intentional.foo/schemas/config.yml
contract: contract-1
settings:
  internal-dependency-bump: patch
  pre-1-0-bump-mapping: compatibility
discovery:
  managed-paths:
  - detector: go-module
    path: go.mod
    release-unit: gitpr
release-units:
  gitpr:
    path: .
    projections:
    - adapter: go
      file: go.mod
      mode: none
    tags:
      primary:
        role: primary
        template: '{version}'
